name: PetPlus
options:
  bundleIdPrefix: com.petplus
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.4"
targets:
  PetPlus:
    type: application
    platform: iOS
    sources:
      - PetPlus
    settings:
      base:
        INFOPLIST_GENERATION: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0
        GENERATE_INFOPLIST_FILE: YES
        ENABLE_PREVIEWS: YES
        SWIFT_EMIT_LOC_STRINGS: YES
